name: Deploy Handmade Project to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/ec2_key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            set -e

            echo "Going to project folder..."
            cd /home/ubuntu/handmade_project

            echo "Pulling latest code from GitHub..."
            git fetch origin main
            git reset --hard origin/main

            echo "Rebuilding Docker containers..."
            sudo docker compose down
            sudo docker compose up -d --build

            echo "Cleaning unused Docker images..."
            sudo docker image prune -f

            echo "Deployment completed. Running containers:"
            sudo docker ps
          '
